apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: cq5en9j3o-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-dotnet-basic:d71b9eeeb2dc2c3faefe1f9731731d2aac30acdd@sha256:72916c1cff5ad32a576bf0c87df6fe8b25f83e9eebed0bdd5d038b29bc3f8504
          name: container-image
