apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: cq5en9j3o-dotnet-basic
  janus-idp.io/tekton: cq5en9j3o-dotnet-basic
  backstage.io/kubernetes-id: cq5en9j3o-dotnet-basic
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: cq5en9j3o-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
